In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

In [2]:
X =  np.array([[1,2,3], [4,5,6]])
print(X)

[[1 2 3]
 [4 5 6]]


In [4]:
# S is vector which containes sorted singular values
U, S, VT = np.linalg.svd(X)
V = VT.T
Sigma = np.zeros(X.shape)
for ss in range(0, S.shape[0]):
    Sigma[ss, ss] = S[ss]

In [5]:
X_SVD = U@Sigma@V.T

In [7]:
print(X_SVD)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
print(U)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]


In [10]:
[Lam, E] = np.linalg.eig(X@X.T)
Lam = np.real(Lam) # eigen value vector
E = np.real(E) # eigen vector matrix
index = Lam.argsort()[::-1]
Lam = Lam[index]
E = E[:, index]
L = np.diag(Lam)
print(E)

[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]


In [11]:
print(Sigma)

[[9.508032   0.         0.        ]
 [0.         0.77286964 0.        ]]


In [12]:
print(np.sqrt(L))

[[9.508032   0.        ]
 [0.         0.77286964]]
